Citation report update
inbo/inbomd_examples pull request #29
Opened 2020-08-19 08:16 UTC by florisvdh

Updates in the section on Better BibTeX (issue solved + a non-issue).

2020-08-19 08:35 UTC, ThierryO requested changes
Looks good, expect for a failing URL.

2020-08-19 08:35 UTC, ThierryO commented on source/citation_style/index.Rmd
> +Zie ook: '[many, but not all, BibTeX styles will correct hyphen to n-dash]( many, but not all, BibTeX styles will correct hyphen to n-dash)'.
I think the URL needs fixing

2020-08-19 09:09 UTC, florisvdh commented on source/citation_style/index.Rmd
> +Zie ook: '[many, but not all, BibTeX styles will correct hyphen to n-dash]( many, but not all, BibTeX styles will correct hyphen to n-dash)'.
well spotted, will fix it

2020-08-19 09:37 UTC, ThierryO approved these changes

2020-08-28 12:07 UTC, florisvdh commented
In attendance of a fix for #28, I upload here the locally rendered files so that they can be compared with the website version after this PR will be merged.

- [citation_style.zip](https://github.com/inbo/inbomd_examples/files/5141942/citation_style.zip) (this is the gitbook)
- [citation_style_bst.pdf](https://github.com/inbo/inbomd_examples/files/5141943/citation_style_bst.pdf)
- [citation_style_csl.pdf](https://github.com/inbo/inbomd_examples/files/5141944/citation_style_csl.pdf)

Done with INBOmd@`6a00c0b`. (current master)

2020-08-28 14:07 UTC, merged